language: ruby

before_install:
  - gem update bundler

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec rake db:setup

rvm:
  - 2.2.2
  - 2.4.0

env:
  - RAILS_VERSION="~> 5.0.0"
  - RAILS_VERSION="~> 5.1.0"

matrix:
  exclude:
    - rvm: 2.0.0
      env: RAILS_VERSION="~> 5.0.0"
    - rvm: 2.1.9
      env: RAILS_VERSION="~> 5.0.0"
  allow_failures:
    - rvm: ruby-head
